name = "first-web-app"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

compatibility_date = "2025-12-05"

[assets]
directory = "./dist"

[build]
command = "pnpm run build"
cwd = "./"

[env.production]
name = "first-web-app-prod"
workers_dev = false
