
name = "jane-bingley"
main = ".open-next/worker.js"
account_id = "8408e907218fe5e182a71e44dd1c6377"
zone_id = "6c0852046caee10d9af0f4897fc17e42"
route = "janebingley.cc/*"
workers_dev = false
preview_urls = false
compatibility_date = "2025-10-08"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

upload_source_maps = true
